export const PROJECT_TOOL_MODULES = {
  Contracting: [
    'Contractor View', 'Contractor Edit', 'Contractor Delete', 'Add Group', 'Register Supplier to Group',
    'Insurance Policy Add', 'Insurance Policy Detail', 'Labour Master', 'Requisition Generation',
    'Requisition Browse', 'Labour Requisition Approve', 'Labour Requisition wise WO Generation',
    'Raise Work Order', 'Edit Work Order', 'Browse Work Order', 'Send Work Order by Email', 'Labour Rate Master',
    'RA Bill Generation', 'RA Bill Browse', 'RA Bill Approval',
    'Enquiry Generation', 'Enquiry Browse', 'Quotation Entry', 'Quotation Browse', 'Quotation Compare',
  ],
  Engineering: [
    'Project View', 'Project Edit', 'Project Delete', 'New Project', 'Contract & Scope Save', 'Lock Baseline',
    'Define WBS', 'WBS Budget / Estimate Allocation', 'Task Library Create', 'Task Library Edit', 'Task Library Delete',
    'Material Library Create', 'Material Library Edit', 'Material Library Delete', 'Equipment Library Create',
    'Equipment Library Edit', 'Equipment Library Delete', 'Labour Library Create', 'Labour Library Edit',
    'Labour Library Delete', 'Unit Master Create', 'Unit Master Edit', 'Unit Master Delete',
    'Project Category 1 Create/Edit/Delete', 'Project Category 2 Create/Edit/Delete',
  ],
  Purchase: [
    'Purchase Indent Create', 'Purchase Indent View', 'Purchase Indent Edit', 'Purchase Indent Approve', 'Send Purchase Indent by Email',
    'Vendor Master Create', 'Vendor Master View', 'Vendor Master Edit', 'Vendor Master Approve', 'Send Vendor Master by Email',
    'Enquiry Generation', 'Enquiry Browse',
    'Quotation Entry', 'Quotation Browse', 'Quotation Compare', 'Purchase Orders Create', 'Purchase Orders View',
    'Purchase Orders Edit', 'Purchase Orders Approve', 'Send Purchase Order by Email', 'PO Material Browse',
    'Purchase Bills Create', 'Purchase Bills View', 'Purchase Bills Edit', 'Purchase Bills Approve', 'Send Purchase Bill by Email',
  ],
  Site: [
    'Site Dashboard', 'DPR Create', 'DPR View', 'Work Completion — Log Qty', 'Material Requisition Raise',
    'Material Requisition Edit', 'Material Requisition Delete', 'GTN View', 'GTN Edit', 'GRN View', 'GRN Edit',
    'Site Store', 'Task Status Change', 'Quality Control View', 'Quality Control Add', 'Health & Safety View',
    'Health & Safety Add', 'Raise NCR',
  ],
  Marketing: [
    'Marketing Dashboard', 'Analytics', 'Lead Register', 'Customer Master',
    'Opportunity Pipeline', 'Tender & Proposal', 'Handover to Project',
  ],
};

export function employeeToolCode(module, name) {
  const slug = name.normalize('NFKD').replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-zA-Z0-9]+/g, '_').replace(/^_+|_+$/g, '').toUpperCase();
  return `EMP_${module.toUpperCase()}_${slug}`;
}

export const PROJECT_EMPLOYEE_TOOLS = Object.fromEntries(
  Object.entries(PROJECT_TOOL_MODULES).map(([module, names]) => [
    module, names.map(name => ({ name, code: employeeToolCode(module, name) })),
  ]),
);

const alias = (module, ...names) => names.map(name => employeeToolCode(module, name));
export const LEGACY_PERMISSION_ALIASES = {
  CONTRACT_CONTRACTOR_LIST: alias('Contracting', 'Contractor View'),
  CONTRACT_CONTRACTOR_EDIT: alias('Contracting', 'Contractor Edit'),
  CONTRACT_CONTRACTOR_DELETE: alias('Contracting', 'Contractor Delete'),
  CONTRACT_ADD_GROUP: alias('Contracting', 'Add Group'),
  CONTRACT_REG_SUPPLIERS: alias('Contracting', 'Register Supplier to Group'),
  CONTRACT_INSURANCE_POLICY: alias('Contracting', 'Insurance Policy Add', 'Insurance Policy Detail'),
  CONTRACT_LABOUR_MASTER: alias('Contracting', 'Labour Master'),
  CONTRACT_REQ_GEN: alias('Contracting', 'Requisition Generation'),
  CONTRACT_REQ_BROWSE: alias('Contracting', 'Requisition Browse'),
  CONTRACT_REQ_APPROVE: alias('Contracting', 'Labour Requisition Approve'),
  CONTRACT_REQ_WO_GEN: alias('Contracting', 'Labour Requisition wise WO Generation'),
  CONTRACT_WO_RAISE: alias('Contracting', 'Raise Work Order'),
  CONTRACT_WO_BROWSE: alias('Contracting', 'Raise Work Order', 'Browse Work Order', 'Edit Work Order', 'Send Work Order by Email'),
  CONTRACT_WO_EDIT: alias('Contracting', 'Edit Work Order'),
  CONTRACT_WO_EMAIL: alias('Contracting', 'Send Work Order by Email'),
  CONTRACT_WO_PAGE: alias('Contracting', 'Raise Work Order', 'Browse Work Order', 'Edit Work Order', 'Send Work Order by Email'),
  CONTRACT_LABOUR_RATE_MASTER: alias('Contracting', 'Labour Rate Master'),
  CONTRACT_RA_GEN: alias('Contracting', 'RA Bill Generation'),
  CONTRACT_RA_BROWSE: alias('Contracting', 'RA Bill Browse'),
  CONTRACT_RA_APPROVAL: alias('Contracting', 'RA Bill Approval'),
  CONTRACT_RA_PAGE: alias('Contracting', 'RA Bill Generation', 'RA Bill Browse', 'RA Bill Approval'),
  CONTRACT_RA_ADVANCE: alias('Contracting', 'RA Bill Approval'),
  CONTRACT_ENQUIRY_GEN: alias('Contracting', 'Enquiry Generation'),
  CONTRACT_ENQUIRY_BROWSE: alias('Contracting', 'Enquiry Browse'),
  CONTRACT_QUOTATION_ENTRY: alias('Contracting', 'Quotation Entry'),
  CONTRACT_QUOTATION_BROWSE: alias('Contracting', 'Quotation Browse'),
  CONTRACT_QUOTATION_COMPARE: alias('Contracting', 'Quotation Compare'),
  ENGG_PROJECT_DASHBOARD: alias('Engineering', 'Project View'),
  ENGG_PROJECT_MASTER: alias('Engineering', 'Project View', 'Project Edit', 'Project Delete'),
  ENGG_PROJECT_CREATE: alias('Engineering', 'New Project'),
  ENGG_CONTRACT_SCOPE: alias('Engineering', 'Contract & Scope Save', 'Lock Baseline'),
  ENGG_TEAM_ALLOCATION: alias('Engineering', 'Project Edit'),
  ENGG_DEFINE_WBS: alias('Engineering', 'Define WBS'),
  ENGG_WBS_BUDGET: alias('Engineering', 'WBS Budget / Estimate Allocation'),
  ENGG_BUDGET_TXN_BROWSE: alias('Engineering', 'WBS Budget / Estimate Allocation'),
  ENGG_LIBRARY_MANAGER: alias('Engineering', 'Task Library Create', 'Material Library Create', 'Equipment Library Create', 'Labour Library Create'),
  ENGG_TASK_LIBRARY: alias('Engineering', 'Task Library Create', 'Task Library Edit', 'Task Library Delete'),
  ENGG_MATERIAL_LIBRARY: alias('Engineering', 'Material Library Create', 'Material Library Edit', 'Material Library Delete'),
  ENGG_EQUIPMENT_LIBRARY: alias('Engineering', 'Equipment Library Create', 'Equipment Library Edit', 'Equipment Library Delete'),
  ENGG_LABOUR_LIBRARY: alias('Engineering', 'Labour Library Create', 'Labour Library Edit', 'Labour Library Delete'),
  ENGG_UNIT_MASTER: alias('Engineering', 'Unit Master Create', 'Unit Master Edit', 'Unit Master Delete'),
  ENGG_PROJECT_CATEGORY_1: alias('Engineering', 'Project Category 1 Create/Edit/Delete'),
  ENGG_PROJECT_CATEGORY_2: alias('Engineering', 'Project Category 2 Create/Edit/Delete'),
  PURCHASE_DASHBOARD: alias('Purchase', ...PROJECT_TOOL_MODULES.Purchase),
  PURCHASE_PR: alias('Purchase', 'Purchase Indent Create', 'Purchase Indent View', 'Purchase Indent Edit', 'Purchase Indent Approve', 'Send Purchase Indent by Email'),
  PURCHASE_PR_CREATE: alias('Purchase', 'Purchase Indent Create'),
  PURCHASE_PR_VIEW: alias('Purchase', 'Purchase Indent View'),
  PURCHASE_PR_EDIT: alias('Purchase', 'Purchase Indent Edit'),
  PURCHASE_PR_APPROVE: alias('Purchase', 'Purchase Indent Approve'),
  PURCHASE_PR_EMAIL: alias('Purchase', 'Send Purchase Indent by Email'),
  PURCHASE_VENDOR_MASTER: alias('Purchase', 'Vendor Master Create', 'Vendor Master View', 'Vendor Master Edit', 'Vendor Master Approve', 'Send Vendor Master by Email'),
  PURCHASE_VENDOR_CREATE: alias('Purchase', 'Vendor Master Create'),
  PURCHASE_VENDOR_VIEW: alias('Purchase', 'Vendor Master View'),
  PURCHASE_VENDOR_EDIT: alias('Purchase', 'Vendor Master Edit'),
  PURCHASE_VENDOR_APPROVE: alias('Purchase', 'Vendor Master Approve'),
  PURCHASE_VENDOR_EMAIL: alias('Purchase', 'Send Vendor Master by Email'),
  PURCHASE_BRAND_MASTER: [],
  PURCHASE_ENQUIRY_GENERATION: alias('Purchase', 'Enquiry Generation'),
  PURCHASE_ENQUIRY_BROWSE: alias('Purchase', 'Enquiry Browse'),
  PURCHASE_QUOTATION: alias('Purchase', 'Quotation Entry', 'Quotation Browse', 'Quotation Compare'),
  PURCHASE_PO: alias('Purchase', 'Purchase Orders Create', 'Purchase Orders View', 'Purchase Orders Edit', 'Purchase Orders Approve', 'Send Purchase Order by Email'),
  PURCHASE_PO_CREATE: alias('Purchase', 'Purchase Orders Create'),
  PURCHASE_PO_VIEW: alias('Purchase', 'Purchase Orders View'),
  PURCHASE_PO_EDIT: alias('Purchase', 'Purchase Orders Edit'),
  PURCHASE_PO_APPROVE: alias('Purchase', 'Purchase Orders Approve'),
  PURCHASE_PO_EMAIL: alias('Purchase', 'Send Purchase Order by Email'),
  PURCHASE_PO_BROWSE: alias('Purchase', 'PO Material Browse'),
  PURCHASE_ADVANCE: [],
  PURCHASE_BILLS: alias('Purchase', 'Purchase Bills Create', 'Purchase Bills View', 'Purchase Bills Edit', 'Purchase Bills Approve', 'Send Purchase Bill by Email'),
  PURCHASE_BILLS_CREATE: alias('Purchase', 'Purchase Bills Create'),
  PURCHASE_BILLS_VIEW: alias('Purchase', 'Purchase Bills View'),
  PURCHASE_BILLS_EDIT: alias('Purchase', 'Purchase Bills Edit'),
  PURCHASE_BILLS_APPROVE: alias('Purchase', 'Purchase Bills Approve'),
  PURCHASE_BILLS_EMAIL: alias('Purchase', 'Send Purchase Bill by Email'),
  SITE_DASHBOARD: alias('Site', 'Site Dashboard'),
  SITE_DPR: alias('Site', 'DPR Create', 'DPR View'),
  SITE_WORK_COMPLETION: alias('Site', 'Work Completion — Log Qty'),
  SITE_MATERIAL_REQUISITION: alias('Site', 'Material Requisition Raise', 'Material Requisition Edit', 'Material Requisition Delete'),
  SITE_GTN: alias('Site', 'GTN View', 'GTN Edit'),
  SITE_GRN: alias('Site', 'GRN View', 'GRN Edit'),
  SITE_STORE: alias('Site', 'Site Store'),
  SITE_TASK_STATUS: alias('Site', 'Task Status Change'),
  SITE_QUALITY: alias('Site', 'Quality Control View', 'Quality Control Add', 'Health & Safety View', 'Health & Safety Add', 'Raise NCR'),

  MARKETING_DASHBOARD: alias('Marketing', 'Marketing Dashboard'),
  MARKETING_ANALYTICS: alias('Marketing', 'Analytics'),
  MARKETING_LEAD_REGISTER: alias('Marketing', 'Lead Register'),
  MARKETING_CUSTOMER_MASTER: alias('Marketing', 'Customer Master'),
  MARKETING_OPP_PIPELINE: alias('Marketing', 'Opportunity Pipeline'),
  MARKETING_TENDER_PROPOSAL: alias('Marketing', 'Tender & Proposal'),
  MARKETING_HANDOVER: alias('Marketing', 'Handover to Project'),
};
