ALTER TABLE "TripLog"
ADD COLUMN "startLatitude" DOUBLE PRECISION,
ADD COLUMN "startLongitude" DOUBLE PRECISION,
ADD COLUMN "endLatitude" DOUBLE PRECISION,
ADD COLUMN "endLongitude" DOUBLE PRECISION,
ADD COLUMN "routePath" JSONB;
